/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWorkoutsRouteImport } from './routes/dashboard/workouts'
import { Route as DashboardObjetivesRouteImport } from './routes/dashboard/objetives'
import { Route as DashboardGymdaysRouteImport } from './routes/dashboard/gymdays'
import { Route as DashboardGoalsRouteImport } from './routes/dashboard/goals'
import { Route as DashboardExcercicesRouteImport } from './routes/dashboard/excercices'
import { Route as AuthRegistrationRouteImport } from './routes/auth/registration'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardGymdaysGymDayIdRouteImport } from './routes/dashboard/gymdays.$gymDayId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWorkoutsRoute = DashboardWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardObjetivesRoute = DashboardObjetivesRouteImport.update({
  id: '/objetives',
  path: '/objetives',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGymdaysRoute = DashboardGymdaysRouteImport.update({
  id: '/gymdays',
  path: '/gymdays',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGoalsRoute = DashboardGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExcercicesRoute = DashboardExcercicesRouteImport.update({
  id: '/excercices',
  path: '/excercices',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegistrationRoute = AuthRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardGymdaysGymDayIdRoute =
  DashboardGymdaysGymDayIdRouteImport.update({
    id: '/$gymDayId',
    path: '/$gymDayId',
    getParentRoute: () => DashboardGymdaysRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/dashboard/excercices': typeof DashboardExcercicesRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/gymdays': typeof DashboardGymdaysRouteWithChildren
  '/dashboard/objetives': typeof DashboardObjetivesRoute
  '/dashboard/workouts': typeof DashboardWorkoutsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/gymdays/$gymDayId': typeof DashboardGymdaysGymDayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/dashboard/excercices': typeof DashboardExcercicesRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/gymdays': typeof DashboardGymdaysRouteWithChildren
  '/dashboard/objetives': typeof DashboardObjetivesRoute
  '/dashboard/workouts': typeof DashboardWorkoutsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/gymdays/$gymDayId': typeof DashboardGymdaysGymDayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/dashboard/excercices': typeof DashboardExcercicesRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/gymdays': typeof DashboardGymdaysRouteWithChildren
  '/dashboard/objetives': typeof DashboardObjetivesRoute
  '/dashboard/workouts': typeof DashboardWorkoutsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/gymdays/$gymDayId': typeof DashboardGymdaysGymDayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/registration'
    | '/dashboard/excercices'
    | '/dashboard/goals'
    | '/dashboard/gymdays'
    | '/dashboard/objetives'
    | '/dashboard/workouts'
    | '/dashboard/'
    | '/dashboard/gymdays/$gymDayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/registration'
    | '/dashboard/excercices'
    | '/dashboard/goals'
    | '/dashboard/gymdays'
    | '/dashboard/objetives'
    | '/dashboard/workouts'
    | '/dashboard'
    | '/dashboard/gymdays/$gymDayId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/registration'
    | '/dashboard/excercices'
    | '/dashboard/goals'
    | '/dashboard/gymdays'
    | '/dashboard/objetives'
    | '/dashboard/workouts'
    | '/dashboard/'
    | '/dashboard/gymdays/$gymDayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/workouts': {
      id: '/dashboard/workouts'
      path: '/workouts'
      fullPath: '/dashboard/workouts'
      preLoaderRoute: typeof DashboardWorkoutsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/objetives': {
      id: '/dashboard/objetives'
      path: '/objetives'
      fullPath: '/dashboard/objetives'
      preLoaderRoute: typeof DashboardObjetivesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/gymdays': {
      id: '/dashboard/gymdays'
      path: '/gymdays'
      fullPath: '/dashboard/gymdays'
      preLoaderRoute: typeof DashboardGymdaysRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/goals': {
      id: '/dashboard/goals'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof DashboardGoalsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/excercices': {
      id: '/dashboard/excercices'
      path: '/excercices'
      fullPath: '/dashboard/excercices'
      preLoaderRoute: typeof DashboardExcercicesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/registration': {
      id: '/auth/registration'
      path: '/registration'
      fullPath: '/auth/registration'
      preLoaderRoute: typeof AuthRegistrationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/gymdays/$gymDayId': {
      id: '/dashboard/gymdays/$gymDayId'
      path: '/$gymDayId'
      fullPath: '/dashboard/gymdays/$gymDayId'
      preLoaderRoute: typeof DashboardGymdaysGymDayIdRouteImport
      parentRoute: typeof DashboardGymdaysRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegistrationRoute: typeof AuthRegistrationRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegistrationRoute: AuthRegistrationRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardGymdaysRouteChildren {
  DashboardGymdaysGymDayIdRoute: typeof DashboardGymdaysGymDayIdRoute
}

const DashboardGymdaysRouteChildren: DashboardGymdaysRouteChildren = {
  DashboardGymdaysGymDayIdRoute: DashboardGymdaysGymDayIdRoute,
}

const DashboardGymdaysRouteWithChildren =
  DashboardGymdaysRoute._addFileChildren(DashboardGymdaysRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardExcercicesRoute: typeof DashboardExcercicesRoute
  DashboardGoalsRoute: typeof DashboardGoalsRoute
  DashboardGymdaysRoute: typeof DashboardGymdaysRouteWithChildren
  DashboardObjetivesRoute: typeof DashboardObjetivesRoute
  DashboardWorkoutsRoute: typeof DashboardWorkoutsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardExcercicesRoute: DashboardExcercicesRoute,
  DashboardGoalsRoute: DashboardGoalsRoute,
  DashboardGymdaysRoute: DashboardGymdaysRouteWithChildren,
  DashboardObjetivesRoute: DashboardObjetivesRoute,
  DashboardWorkoutsRoute: DashboardWorkoutsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
